### ISSUE TITLE
能否不用redis，小项目不需要配reids

### ISSUE THREAD

**Issue by fangjun953322** [dashiell-zhang/NetEngine#5]
能否不用redis，小项目不需要配reids

**Comment by dashiell-zhang** [comment]
目前架构设计必须要用到 redis ，主要是其中的分布式锁模块，缓存模块和 雪花ID 的注册模块，需要依赖到 reids

**Comment by dashiell-zhang** [comment]
如果需要 windows 版的 redis 可以用 [https://github.com/redis-windows/redis-windows](https://github.com/redis-windows/redis-windows) 这个
