### ISSUE TITLE
CronHelper中可否根据传入的参数转换为Cron表达式呢

### ISSUE THREAD

**Issue by Necey** [dashiell-zhang/NetEngine#6]
大佬您好，我研究了一下只看到解析Cron表达式的方法，还没有看到将传入的时间等参数转换为Cron表达式的地方，如果有的话可以麻烦您告知一下吗？谢谢！ 如果没有的话也请教一下您在证书签发平台是如何实现创建定时任务的嘛？

**Comment by dashiell-zhang** [comment]
@Necey  你好，目前没有通过时间转换 cron 的方案，证书签发那边我是配置了 0 1/2 * * * ? 这个表达式，在固定的时间间隔扫描某个时间之前签发的证书
